apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-06-06T19:16:33Z"
  labels:
    app: nginx
  name: nginx
  namespace: default
  resourceVersion: "720"
  uid: e5bf7b60-03bb-449a-9038-abdb0161b831
spec:
  clusterIP: 10.106.210.189
  clusterIPs:
  - 10.106.210.189
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30235
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
